### ISSUE TITLE
Filepath issue when running takari lifecycle in m2e on Windows 8.1

### ISSUE THREAD

**Issue by jwachter** [takari/io.takari.m2e.lifecycle#1]
I tried out the latest takari-lifecycle-plugin (1.11.5) and Eclipse Integration (0.1.0.201505181451) together with Eclipse Mars M7 on Windows 8.1.

When creating a Maven Project with packaging type `takari-jar` there is an immediate exception thrown during project configuration:

```
Execution m2e-takari-lifecycle:default-jar:pom-properties of goal io.takari.maven.plugins:takari-lifecycle-plugin:1.11.4:pom-properties failed: Illegal char <:> at index 170: D:\Temp\eclipse-takari\git\takari-lifecycle\takari-lifecycle-plugin\target\incremental\io.takari.maven.plugins_takari-lifecycle-plugin_pom-properties_m2e-takari-lifecycle:default-jar:pom-properties (io.takari.maven.plugins:takari-lifecycle-plugin:1.11.4:jar:default-jar:package)

org.apache.maven.plugin.PluginExecutionException: Execution m2e-takari-lifecycle:default-jar:pom-properties of goal io.takari.maven.plugins:takari-lifecycle-plugin:1.11.4:pom-properties failed: Illegal char <:> at index 170: D:\Temp\eclipse-takari\git\takari-lifecycle\takari-lifecycle-plugin\target\incremental\io.takari.maven.plugins_takari-lifecycle-plugin_pom-properties_m2e-takari-lifecycle:default-jar:pom-properties
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 170: D:\Temp\eclipse-takari\git\takari-lifecycle\takari-lifecycle-plugin\target\incremental\io.takari.maven.plugins_takari-lifecycle-plugin_pom-properties_m2e-takari-lifecycle:default-jar:pom-properties
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.io.File.toPath(Unknown Source)
	at io.takari.incrementalbuild.maven.internal.ProjectWorkspace.getWorkspace(ProjectWorkspace.java:43)
	at io.takari.incrementalbuild.maven.internal.ProjectWorkspace.newOutputStream(ProjectWorkspace.java:76)
	at io.takari.incrementalbuild.spi.AbstractBuildContext.commit(AbstractBuildContext.java:510)
	at io.takari.incrementalbuild.maven.internal.MavenBuildContextFinalizer.afterMojoExecutionSuccess(MavenBuildContextFinalizer.java:78)
	at org.apache.maven.execution.scope.internal.MojoExecutionScope.afterMojoExecutionSuccess(MojoExecutionScope.java:163)
	at org.apache.maven.plugin.CompoundMojoExecutionListener.afterMojoExecutionSuccess(CompoundMojoExecutionListener.java:52)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:136)
	... 31 more
```

The issue is that a path containing `:` in the filename is generated which is not possible on Windows. The above exception is from the takari-lifecycle projects themselves when they are imported but it can be easily reproduced using a plain (empty) Maven project with only the takari-lifecycle-plugin and the packaging `takari-jar` defined.

I traced this issue through some debugging back to the `io.takari.m2e.jar.internal.JarProjectConfigurator` respectively the line 34 [1] which defines an execution id with `:` characters (producing `m2e-takari-lifecycle:default-jar:pom-properties`) that will lead the `io.takari.incrementalbuild.maven.internal.MavenIncrementalConventions.getExecutionId(MojoExecution)` method to generate a filename like:

```
<groupid>_<artifactid>_<goal>_<executionid>
```

where executionId than will be used as a file name by `io.takari.incrementalbuild.spi.AbstractBuildContext.commit(MessageSinkAdaptor)`.

I changed the execution id generated by the `JarProjectConfigurator` to use `_` instead of `:` as a separator and at least the exception doesn't occur anymore, but I'm not sure if that is a proper change.

Building projects with Takari Lifecycle through Maven on commandline or e.g. IntelliJ doesn't seem to have issues running on Windows so I assume it's only related to the M2E integration.

[1] https://github.com/takari/io.takari.m2e.lifecycle/blob/cb8c57da253d289c7fff1e3455002bde3b11f6bc/io.takari.m2e.jar/src/io/takari/m2e/jar/internal/JarProjectConfigurator.java#L34

**Comment by Tzrlk** [comment]
+1
